[providers]
python = "3.9"

[variables]
PYTHONPATH = "backend"

[phases.setup]
aptPkgs = ["ffmpeg"]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
